return function(context)
 setfenv(1,context)
 coupleMovementPanel=Instance.new("Frame");coupleMovementPanel.Size=UDim2.new(1,-16,1,-(titleH+20));coupleMovementPanel.Position=UDim2.new(0,8,0,titleH+8);coupleMovementPanel.BackgroundTransparency=1;coupleMovementPanel.Visible=false;coupleMovementPanel.Parent=content
 local c=Instance.new("Frame");c.Size=UDim2.new(1,0,0,330);c.BackgroundColor3=currentTheme.secondary;c.Parent=coupleMovementPanel;Instance.new("UICorner",c).CornerRadius=UDim.new(0,14);RegisterTheme(c,"BackgroundColor3","secondary")
 local function b(t,y,x,w)local v=Instance.new("TextButton");v.Size=UDim2.new(w or 1,-8,0,42);v.Position=UDim2.new(x or 0,4,0,y);v.BackgroundColor3=currentTheme.tertiary;v.Text=t;v.TextColor3=currentTheme.text;v.Font=Enum.Font.GothamBold;v.TextSize=12;v.Parent=c;Instance.new("UICorner",v).CornerRadius=UDim.new(0,10);return v end
 local q=Instance.new("TextBox");q.Size=UDim2.new(1,-16,0,42);q.Position=UDim2.new(0,8,0,10);q.BackgroundColor3=currentTheme.tertiary;q.PlaceholderText=isES and"Nombre o ID del emote"or"Emote name or ID";q.Text="";q.TextColor3=currentTheme.text;q.Font=Enum.Font.GothamMedium;q.TextSize=13;q.Parent=c;Instance.new("UICorner",q).CornerRadius=UDim.new(0,10)
 local find=b(isES and"Buscar y reproducir"or"Find and play",60);local sm,sv,sp=b("−",112,0,.2),b("",112,.2,.6),b("+",112,.8,.2);local bm,bv,bp=b("−",164,0,.2),b("",164,.2,.6),b("+",164,.8,.2);local em,ev,ep=b("−",216,0,.2),b("",216,.2,.6),b("+",216,.8,.2);local save=b(isES and"Guardar bucle"or"Save loop",268);local status=Instance.new("TextLabel");status.Size=UDim2.new(1,-16,0,18);status.Position=UDim2.new(0,8,0,310);status.BackgroundTransparency=1;status.TextColor3=currentTheme.textDim;status.TextSize=11;status.Parent=c
 UpdateCoupleMovementPanel=function(msg)local e=CoupleMovementController:GetSelected();sv.Text=(isES and"Velocidad: "or"Speed: ")..CoupleMovementController.Speed.."x";bv.Text=(isES and"Inicio: "or"Start: ")..CoupleMovementController.StartTime.."s";ev.Text=(isES and"Fin: "or"End: ")..CoupleMovementController.EndTime.."s";if e then q.Text=e.name.." ("..e.id..")"end;if msg then status.Text=msg end end
 find.MouseButton1Click:Connect(function()local e=CoupleMovementController:Find(q.Text);if not e then UpdateCoupleMovementPanel(isES and"Emote no encontrado."or"Emote not found.")return end;local _,m=CoupleMovementController:Preview();UpdateCoupleMovementPanel(m)end)
 sm.MouseButton1Click:Connect(function()CoupleMovementController:SetSpeed(CoupleMovementController.Speed-.5);UpdateCoupleMovementPanel()end);sp.MouseButton1Click:Connect(function()CoupleMovementController:SetSpeed(CoupleMovementController.Speed+.5);UpdateCoupleMovementPanel()end)
 bm.MouseButton1Click:Connect(function()CoupleMovementController:SetStart(CoupleMovementController.StartTime-.5);UpdateCoupleMovementPanel()end);bp.MouseButton1Click:Connect(function()CoupleMovementController:SetStart(CoupleMovementController.StartTime+.5);UpdateCoupleMovementPanel()end)
 em.MouseButton1Click:Connect(function()CoupleMovementController:SetEnd(CoupleMovementController.EndTime-.5);UpdateCoupleMovementPanel()end);ep.MouseButton1Click:Connect(function()CoupleMovementController:SetEnd(CoupleMovementController.EndTime+.5);UpdateCoupleMovementPanel()end)
 save.MouseButton1Click:Connect(function()local ok=CoupleMovementController:SaveLoop();UpdateCoupleMovementPanel(ok and(isES and"Bucle guardado."or"Loop saved.")or(isES and"Selecciona un emote."or"Select an emote."))end);UpdateCoupleMovementPanel();return true
end